export const PROC_UPDATE_REQUEST = 'PROC_UPDATE_REQUEST'
export const PROC_UPDATE_SUCCESS = 'PROC_UPDATE_SUCCESS'
export const PROC_UPDATE_FAIL = 'PROC_UPDATE_FAIL'
export const PROC_UPDATE_RESET = 'PROC_UPDATE_RESET'